import type { ThemeConfig } from './theme';

export interface ThemePreset {
  id: string;
  name: string;
  description: string;
  theme: ThemeConfig;
}

export const THEME_PRESETS: ThemePreset[] = [
  {
    id: 'lumiere-nails',
    name: 'Lumière Nails',
    description: 'Jemný ružovo-zlatý štýl',
    theme: {
      colors: {
        bg:            '#fdf8f5',
        primary:       '#b87c6f',
        primaryDark:   '#9a6459',
        primaryLight:  '#f5e6e3',
        text:          '#2d1b1b',
        textSecondary: '#7a5c5c',
        textMuted:     '#b09090',
        border:        'rgba(184,124,111,0.2)',
        bgSubtle:      '#f9ede9',
        success:       '#16a34a',
        error:         '#ef4444',
        contrast:      '#ffffff',
        overlay:       '#2d1b1b',
        overlayAlpha:  'rgba(45,27,27,0.55)',
        headerBg:      'rgba(253,248,245,0.96)',
        bgDark:        '#2d1b1b',
        warning:       '#fbbf24',
        successLight:  '#dcfce7',
        errorLight:    '#fef2f2',
        infoLight:     '#eff6ff',
        surface:       '#ffffff',
        bgAlt:         '#f5ede9',
        bgCard:        '#ffffff',
      },
      layout: {
        heroType:     'split',
        cardStyle:    'border',
        navPosition:  'top',
        borderRadius: 'rounded',
      },
    },
  },
  {
    id: 'barbershop',
    name: 'Kate Barber',
    description: 'Tmavý prémiový štýl',
    theme: {
      colors: {
        bg:            '#0A0A0A',
        primary:       '#B87333',
        primaryDark:   '#8B5E2A',
        primaryLight:  '#1A1206',
        text:          '#F5F0E8',
        textSecondary: '#C4B8A8',
        textMuted:     '#8A7F75',
        border:        '#2A2A2A',
        bgSubtle:      '#111111',
        success:       '#4CAF50',
        error:         '#ef4444',
        contrast:      '#0A0A0A',
        overlay:       '#000000',
        overlayAlpha:  'rgba(0,0,0,0.65)',
        headerBg:      'rgba(10,10,10,0.92)',
        bgDark:        '#050505',
        warning:       '#B87333',
        successLight:  'rgba(76,175,80,0.15)',
        errorLight:    'rgba(239,68,68,0.15)',
        infoLight:     'rgba(184,115,51,0.1)',
      },
      layout: {
        heroType:     'split',
        cardStyle:    'border',
        navPosition:  'top',
        borderRadius: 'sharp',
      },
    },
  },
  {
    id: 'dark',
    name: 'Dark',
    description: 'Sučasný a štýlový',
    theme: {
      colors: {
        bg:            '#0f172a',
        primary:       '#22c55e',
        primaryDark:   '#16a34a',
        primaryLight:  '#052e16',
        text:          '#f1f5f9',
        textSecondary: '#94a3b8',
        textMuted:     '#64748b',
        border:        '#334155',
        bgSubtle:      '#1e293b',
        success:       '#4ade80',
        error:         '#f87171',
        contrast:      '#ffffff',
        overlay:       '#000000',
        overlayAlpha:  'rgba(0,0,0,0.5)',
        headerBg:      'rgba(15,23,42,0.9)',
        bgDark:        '#0f172a',
        warning:       '#fbbf24',
        successLight:  'rgba(22,163,74,0.15)',
        errorLight:    'rgba(239,68,68,0.15)',
        infoLight:     'rgba(59,130,246,0.15)',
      },
      layout: {
        heroType:     'full-width',
        cardStyle:    'flat',
        navPosition:  'top',
        borderRadius: 'sharp',
      },
    },
  },
  {
    id: 'natural',
    name: 'Natural',
    description: 'Prírodný a ekologický',
    theme: {
      colors: {
        bg:            '#fafaf5',
        primary:       '#15803d',
        primaryDark:   '#166534',
        primaryLight:  '#f0fdf4',
        text:          '#1c1917',
        textSecondary: '#57534e',
        textMuted:     '#a8a29e',
        border:        '#d6d3d1',
        bgSubtle:      '#fafaf9',
        success:       '#22c55e',
        error:         '#ef4444',
        contrast:      '#ffffff',
        overlay:       '#ffffff',
        overlayAlpha:  'rgba(250,250,245,0.85)',
        headerBg:      'rgba(250,250,245,0.9)',
        bgDark:        '#1c1917',
        warning:       '#d97706',
        successLight:  '#ecfccb',
        errorLight:    '#fef2f2',
        infoLight:     '#f0fdf4',
      },
      layout: {
        heroType:     'split',
        cardStyle:    'border',
        navPosition:  'top',
        borderRadius: 'rounded',
      },
    },
  },
  {
    id: 'restaurant',
    name: 'Restaurant',
    description: 'Elegantný reštauračný štýl',
    theme: {
      colors: {
        bg:            '#0a0a0a',
        primary:       '#d4a853',
        primaryDark:   '#b8922e',
        primaryLight:  '#1a1505',
        text:          '#f5f5f5',
        textSecondary: '#cbd5e1',
        textMuted:     '#9ca3af',
        border:        '#222222',
        bgSubtle:      '#1a1a1a',
        success:       '#4ade80',
        error:         '#ef4444',
        contrast:      '#ffffff',
        overlay:       '#000000',
        overlayAlpha:  'rgba(0,0,0,0.6)',
        headerBg:      'rgba(10,10,10,0.9)',
        bgDark:        '#050505',
        warning:       '#d4a853',
        successLight:  'rgba(22,163,74,0.15)',
        errorLight:    'rgba(239,68,68,0.15)',
        infoLight:     'rgba(212,168,83,0.15)',
      },
      layout: {
        heroType:     'full-width',
        cardStyle:    'border',
        navPosition:  'top',
        borderRadius: 'rounded',
      },
    },
  },
  {
    id: 'medical',
    name: 'Medical',
    description: 'Čistý a dôveryhodný',
    theme: {
      colors: {
        bg:            '#ffffff',
        primary:       '#0ea5e9',
        primaryDark:   '#0284c7',
        primaryLight:  '#f0f9ff',
        text:          '#0f172a',
        textSecondary: '#475569',
        textMuted:     '#94a3b8',
        border:        '#e2e8f0',
        bgSubtle:      '#f8fafc',
        success:       '#10b981',
        error:         '#f43f5e',
        contrast:      '#ffffff',
        overlay:       '#ffffff',
        overlayAlpha:  'rgba(255,255,255,0.85)',
        headerBg:      'rgba(255,255,255,0.9)',
        bgDark:        '#0c4a6e',
        warning:       '#f59e0b',
        successLight:  '#dcfce7',
        errorLight:    '#fef2f2',
        infoLight:     '#e0f2fe',
      },
      layout: {
        heroType:     'minimal',
        cardStyle:    'border',
        navPosition:  'top',
        borderRadius: 'rounded',
      },
    },
  },
];
