import type { ThemeConfig } from './theme';

export interface ThemePreset {
  id: string;
  name: string;
  description: string;
  theme: ThemeConfig;
}

export const THEME_PRESETS: ThemePreset[] = [
  {
    id: 'electromarket',
    name: 'ElectroMarket',
    description: 'Сучасний магазин електроніки',
    theme: {
      colors: {
        bg: '#fffbf5',
        primary: '#ea580c',
        primaryDark: '#c2410c',
        primaryLight: '#fff7ed',
        text: '#292524',
        textSecondary: '#78716c',
        textMuted: '#a8a29e',
        border: '#e7e5e4',
        bgSubtle: '#fafaf9',
        success: '#15803d',
        error: '#dc2626',
        contrast: '#ffffff',
        overlay: '#ffffff',
        overlayAlpha: 'rgba(255,251,245,0.85)',
        headerBg: 'rgba(255,251,245,0.9)',
        bgDark: '#292524',
        warning: '#f59e0b',
        successLight: '#dcfce7',
        errorLight: '#fef2f2',
        infoLight: '#fef3c7',
      },
      layout: {
        heroType: 'split',
        cardStyle: 'border',
        navPosition: 'top',
        borderRadius: 'rounded',
      },
    },
  },
  {
    id: 'dark',
    name: 'Dark',
    description: 'Сучасний та стильний',
    theme: {
      colors: {
        bg: '#0f172a',
        primary: '#22c55e',
        primaryDark: '#16a34a',
        primaryLight: '#052e16',
        text: '#f1f5f9',
        textSecondary: '#94a3b8',
        textMuted: '#64748b',
        border: '#334155',
        bgSubtle: '#1e293b',
        success: '#4ade80',
        error: '#f87171',
        contrast: '#ffffff',
        overlay: '#000000',
        overlayAlpha: 'rgba(0,0,0,0.5)',
        headerBg: 'rgba(15,23,42,0.9)',
        bgDark: '#0f172a',
        warning: '#fbbf24',
        successLight: 'rgba(22,163,74,0.15)',
        errorLight: 'rgba(239,68,68,0.15)',
        infoLight: 'rgba(59,130,246,0.15)',
      },
      layout: {
        heroType: 'full-width',
        cardStyle: 'flat',
        navPosition: 'top',
        borderRadius: 'sharp',
      },
    },
  },
  {
    id: 'natural',
    name: 'Natural',
    description: 'Природний та екологічний',
    theme: {
      colors: {
        bg: '#fafaf5',
        primary: '#15803d',
        primaryDark: '#166534',
        primaryLight: '#f0fdf4',
        text: '#1c1917',
        textSecondary: '#57534e',
        textMuted: '#a8a29e',
        border: '#d6d3d1',
        bgSubtle: '#fafaf9',
        success: '#22c55e',
        error: '#ef4444',
        contrast: '#ffffff',
        overlay: '#ffffff',
        overlayAlpha: 'rgba(250,250,245,0.85)',
        headerBg: 'rgba(250,250,245,0.9)',
        bgDark: '#1c1917',
        warning: '#d97706',
        successLight: '#ecfccb',
        errorLight: '#fef2f2',
        infoLight: '#f0fdf4',
      },
      layout: {
        heroType: 'split',
        cardStyle: 'border',
        navPosition: 'top',
        borderRadius: 'rounded',
      },
    },
  },
  {
    id: 'medical',
    name: 'Medical',
    description: 'Чистий та довірливий',
    theme: {
      colors: {
        bg: '#ffffff',
        primary: '#0ea5e9',
        primaryDark: '#0284c7',
        primaryLight: '#f0f9ff',
        text: '#0f172a',
        textSecondary: '#475569',
        textMuted: '#94a3b8',
        border: '#e2e8f0',
        bgSubtle: '#f8fafc',
        success: '#10b981',
        error: '#f43f5e',
        contrast: '#ffffff',
        overlay: '#ffffff',
        overlayAlpha: 'rgba(255,255,255,0.85)',
        headerBg: 'rgba(255,255,255,0.9)',
        bgDark: '#0c4a6e',
        warning: '#f59e0b',
        successLight: '#dcfce7',
        errorLight: '#fef2f2',
        infoLight: '#e0f2fe',
      },
      layout: {
        heroType: 'minimal',
        cardStyle: 'border',
        navPosition: 'top',
        borderRadius: 'rounded',
      },
    },
  },
  {
    id: 'food_market',
    name: 'Food Market',
    description: 'Свіжий продуктовий стиль',
    theme: {
      colors: {
        bg: '#fafaf5',
        primary: '#4d7c0f',
        primaryDark: '#365314',
        primaryLight: '#f0fdf4',
        text: '#1a1a1a',
        textSecondary: '#4b5563',
        textMuted: '#6b7280',
        border: '#e5e7d8',
        bgSubtle: '#f5f5f0',
        success: '#16a34a',
        error: '#ef4444',
        contrast: '#ffffff',
        overlay: '#ffffff',
        overlayAlpha: 'rgba(250,250,245,0.85)',
        headerBg: 'rgba(250,250,245,0.92)',
        bgDark: '#1a2e05',
        warning: '#d97706',
        successLight: '#dcfce7',
        errorLight: '#fef2f2',
        infoLight: '#ecfccb',
      },
      layout: {
        heroType: 'full-width',
        cardStyle: 'shadow',
        navPosition: 'top',
        borderRadius: 'rounded',
      },
    },
  },
  {
    id: 'shoe_market',
    name: 'Shoe Market',
    description: 'Когнак та шкіра — преміальне взуття',
    theme: {
      colors: {
        bg: '#fdf8f5',
        primary: '#A0714F',
        primaryDark: '#7d5538',
        primaryLight: '#fdf0e8',
        text: '#1c1410',
        textSecondary: '#6b5b52',
        textMuted: '#a89990',
        border: '#e8ddd6',
        bgSubtle: '#f5ede8',
        success: '#2d7a4f',
        error: '#c0392b',
        contrast: '#ffffff',
        overlay: '#ffffff',
        overlayAlpha: 'rgba(253,248,245,0.88)',
        headerBg: 'rgba(253,248,245,0.92)',
        bgDark: '#1c1410',
        warning: '#c87941',
        successLight: '#d4edda',
        errorLight: '#fde8e8',
        infoLight: '#fdf0e8',
      },
      layout: {
        heroType: 'split',
        cardStyle: 'border',
        navPosition: 'top',
        borderRadius: 'rounded',
      },
    },
  },
  {
    id: 'restaurant',
    name: 'Restaurant',
    description: 'Елегантний ресторанний стиль',
    theme: {
      colors: {
        bg: '#0a0a0a',
        primary: '#d4a853',
        primaryDark: '#b8922e',
        primaryLight: '#1a1505',
        text: '#f5f5f5',
        textSecondary: '#cbd5e1',
        textMuted: '#9ca3af',
        border: '#222222',
        bgSubtle: '#1a1a1a',
        success: '#4ade80',
        error: '#ef4444',
        contrast: '#ffffff',
        overlay: '#000000',
        overlayAlpha: 'rgba(0,0,0,0.6)',
        headerBg: 'rgba(10,10,10,0.9)',
        bgDark: '#050505',
        warning: '#d4a853',
        successLight: 'rgba(22,163,74,0.15)',
        errorLight: 'rgba(239,68,68,0.15)',
        infoLight: 'rgba(212,168,83,0.15)',
      },
      layout: {
        heroType: 'full-width',
        cardStyle: 'border',
        navPosition: 'top',
        borderRadius: 'rounded',
      },
    },
  },
];
